name: Build and Deploy to Netlify

on: [push, pull_request]

jobs:
    build_and_deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 2.6
                  bundler-cache: true
            - name: Build with jekyll
              run: JEKYLL_ENV=production bundle exec jekyll build
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.1
              with:
                  publish-dir: _site
                  production-branch: master
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: 'Deploy from GitHub Actions'
                  enable-pull-request-comment: true
                  enable-commit-comment: false
                  overwrites-pull-request-comment: true
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
