name: Build and Deploy

on: [push, pull_request]

jobs:
    build_and_deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: '0.135.0'
                  extended: true
            - name: Setup NodeJS Runtime
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
            - name: Install dependencies
              run: yarn install
            - name: Build the site
              run: yarn run build
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              if: github.ref == 'refs/heads/master'
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-azP --delete-after"
                  SOURCE: "public/"
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
